package com.attendance.roleAndPermissionService.RoleAndPermissionService.enums;

public enum MessageEnum {

    ROLE_ALREADY_EXIST("ROLE ALREADY EXIST"),
    ROLE_CREATE_SUCCESSFUL("ROLE CREATE SUCCESSFUL"),
    ROLES_FETCHED_SUCCESSFUL("ROLE FETCH SUCCESSFUL"),
    CREATE_NEW_CANTEEN_MENU("CREATE NEW CANTEEN MENU"),
    UPDATE_EXISTING_CANTEEN_MENU("UPDATE EXISTING CANTEEN MENU"),
    DELETE_MENU("DELETE MENU"),
    VIEW_MENU("VIEW MENU"),
    STUDENT_PLACE_ORDER("STUDENT PLACE ORDER"),
    VIEW_OWN_OR_ALL_ORDER("VIEW OWN OR ALL ORDER"),
    CANCEL_AN_ORDER("CANCEL AN ORDER"),
    ADD_OR_REMOVE_CANTEEN_STAFF("ADD OR REMOVE CANTEEN STAFF"),
    TRACK_AND_UPDATE_INGREDIENTS_INVENTOR("TRACK AND UPDATE INGREDIENTS INVENTOR"),
    VIEW_CANTEEN_SALE_REPORT("VIEW CANTEEN SALE REPORT"),
    ASSIGN_ROLES_TO_USER("ASSIGN ROLES TO USER"),
    CREATE_UPDATE_DELETE_USER_ACCOUNTS("CREATE UPDATE DELETE USER ACCOUNTS"),
    ADMIN_FULL_PERMISSION("ADMIN FULL PERMISSION"),
    INVALID_ROLE_OR_PERMISSION("INVALID ROLE OR PERMISSION"),
    ROLE_NOT_FOUND("ROLE NOT FOUND"),
    INVALID_PERMISSION("INVALID PERMISSION"),
    PERMISSION_ASSIGN("PERMISSION_ASSIGN"),
    PERMISSION_REMOVE_FROM_ROLE_SUCCESS("PERMISSION: '%s' REMOVE FROM ROLE: '%s' SUCCESSFUL"),
    ROLE_DELETE("ROLE: '%s' DELETE"),
    PERMISSION_FETCH_BY_ROLE("Permissions fetched successfully for role ['%s']"),
    ROLE_UPDATED("Role '%s' updated to '%s' successfully."),
    ROLE_FETCH("ROLE: '%s' FETCH SUCCESS"),
    PERMISSION_ADD_TO_ROLE("PERMISSION ADD TO ROLE: '%s'"),
    REGISTER_USER_ACCOUNT("REGISTER USER ACCOUNT"),

    MANAGEMENT("MANAGEMENT"),
    ATTENDANCE_MANAGEMENT("ATTENDANCE_MANAGEMENT"),
    ACADEMIC_OPERATION("ACADEMIC_OPERATION"),
    DEPARTMENTAL_MANAGEMENT("DEPARTMENTAL_MANAGEMENT"),
    SYSTEM_ADMINISTRATION("SYSTEM_ADMINISTRATION"),
    HEALTHY("HEALTHY");

    private final String meessage;

    MessageEnum(String meessage){

        this.meessage = meessage;
    }

    public String getMeessage(){
        return meessage;
    }

    public String format(Object... args) {
        return String.format(this.meessage, args);
    }
}
